# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{lighthouse_cli}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Maxim Chernyak"]
  s.date = %q{2009-09-01}
  s.default_executable = %q{lh}
  s.description = %q{A quick command line interface to lighthouse. The goal is to reduce overhead of tracking tickets inline with normal workflow. The effect is achieved by setting conventions.}
  s.email = %q{max@bitsonnet.com}
  s.executables = ["lh"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "Lhcfile",
     "Lhcfile",
     "Rakefile",
     "VERSION",
     "bin/lh",
     "lib/lighthouse_cli.rb",
     "lighthouse_cli.gemspec",
     "test/lighthouse_cli_test.rb",
     "test/test_helper.rb",
     "vendor/lighthouse-api/LICENSE",
     "vendor/lighthouse-api/LICENSE",
     "vendor/lighthouse-api/README.markdown",
     "vendor/lighthouse-api/README.markdown",
     "vendor/lighthouse-api/lib/lighthouse-api.rb",
     "vendor/lighthouse-api/lib/lighthouse-api.rb",
     "vendor/lighthouse-api/lib/lighthouse.rb",
     "vendor/lighthouse-api/lib/lighthouse.rb",
     "vendor/lighthouse-api/lib/lighthouse/console.rb",
     "vendor/lighthouse-api/lib/lighthouse/console.rb"
  ]
  s.homepage = %q{http://github.com/maxim/lighthouse_cli}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A quick command line interface to lighthouse.}
  s.test_files = [
    "test/lighthouse_cli_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<cldwalker-hirb>, [">= 0"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<cldwalker-hirb>, [">= 0"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<cldwalker-hirb>, [">= 0"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end
